ports:
  - 9092

links:
  - zookeeper

extraHosts:
  - kafka:127.0.0.1

env:
  KAFKA_ADVERTISED_HOST_NAME: kafka
  KAFKA_ADVERTISED_PORT: 9092
  KAFKA_BROKER_ID: 1
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  /var/run/docker.sock: /var/run/docker.sock

healthChecks:
  logPatterns:
    - pattern: started \(kafka\.server\.KafkaServer\)
      timeout: 10000
